### ISSUE TITLE
[Suggestion] Get player prefix instead of just group?

### ISSUE THREAD

**Issue by leelawd** [FabioZumbi12/UltimateChat-Sponge#2]
I noticed that the options in the config allowed you to pull the prefix of the group the player is in but did not see anything in regards to player option'd prefix's.

For example
![image](https://cloud.githubusercontent.com/assets/3026728/23639460/cbd97042-02df-11e7-933e-f653d8c2754e.png)

I want the chat to display the tag inherited from self (the player) instead of from default (the group) but if the player no longer has the prefix he has set for himself, it should restore to the default.

**Comment by FabioZumbi12** [comment]
Yes, you can, See the config reader for placeholders {options_<option>} where you can put the permissions options like prefix and suffix.

What you is:
`" - {option_prefix}: Get the prefix of group (if set);\n"`

**Comment by leelawd** [comment]
This only gets the group prefix, not the player prefix.

![image](https://cloud.githubusercontent.com/assets/3026728/23654639/8709ee3e-0329-11e7-8a6b-4284695c9e0f.png)

**Comment by leelawd** [comment]
As i have said previously, This ONLY returns the group prefix. and NOT the players prefix. after removing the group prefix this is what i am left with in chat.

![image](https://cloud.githubusercontent.com/assets/3026728/23654944/f542f5e8-032a-11e7-82f1-587ec2d00643.png)

**Comment by leelawd** [comment]
https://i.gyazo.com/c66be1c3a636059c020cab932303c7cf.mp4

Here is a GIF of the problems. At the end it shows the config file as you will see, the options are set correctly.

This will also not pick up the Nucleus nickname either.
