### ISSUE TITLE
Issues with Nicknames and chat formatting 

### ISSUE THREAD

**Issue by VictiniPower** [FabioZumbi12/UltimateChat-Sponge#3]
In game when a player looks at the chat, 1) The nicknames given by nucleus don't show up and 2) after the player's name is displayed a colon is added. Don't know what I need to show but I know i didn't add the colon somewhere because it automatically resets formatting.

**Comment by FabioZumbi12** [comment]
Try the latest version: http://158.69.121.149:8080/job/UltimateChat/
